[package]
name = "monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
ysyx_macro = { path = "../ysyx_macro" }
msg_resp = { path = "../msg_resp" }
simulator = { path = "../simulator" }
clap = { version = "4.5.26", features = ["derive", "cargo", "color"] }
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_warn"] }
slog-async = "2.8.0"
slog-term = "2.9.1"
rustyline = { version = "15.0.0", features = ["derive"] }
libloading = "0.8.6"
owo-colors = {workspace = true}
ctrlc = "3.4.5"
dlopen2 = "0.7.0"
