[workspace]
resolver = "2"
members = ["monitor", "msg_resp", "core", "ysyx_macro", "simulator", "state", "debug"]

[profile.release]
codegen-units = 1
lto           = true
panic         = "abort"
strip         = true

[workspace.dependencies]
criterion = "0.5.1"
owo-colors = "4.1.0"
rand = "0.9.0"
dlopen2 = "0.7.0"
tabwriter = "1.4.1"
parking_lot = "0.12.3"

[workspace.features]
default = [
    "nemu", 
    "riscv32",
    "differtest",
]

nemu = []
npc = []
ysyxsoc = []

riscv32 = []
riscv64 = []
loongarch32 = []

differtest = []
timetrace = []
