[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = {workspace = true}

[dependencies]
ysyx_macro = { path = "../ysyx_macro" }
msg_resp = { path = "../msg_resp" }
state = { path = "../state" }
winnow = "0.6.24"
llvm-sys = {version = "181.0.0",features = ["prefer-dynamic"]}
rand = {workspace = true}
circular-queue = "0.2.6"
owo-colors = {workspace = true}
dlopen2 = {workspace = true}

[[bench]]
name = "decode_bench"
harness = false
path = "benches/nemu/decode_bench.rs"

[features]
default = ["nemu"]
nemu = []
npc = []
ysyxsoc = []
